Chore: Create new dimension always_exclude for exclusions which applies to all production data analyses
mattermost/mattermost-looker pull request #985
Opened 2024-02-12 18:47 UTC by sri-byte

Impact: Creates a new dimension `always_exclude` for exclusions which applies to all production data analyses.

#### Summary

#### Ticket Link

2024-02-13 11:08 UTC, catalintomai approved these changes

2024-02-13 11:36 UTC, ifoukarakis requested changes

2024-02-13 11:36 UTC, ifoukarakis commented on views/marts/product/dim_excludable_servers.view.lkml
> +    sql:  ${has_reason_single_day_security_only} or ${has_reason_custom_build_version_format} or ${has_reason_single_day_server_side_telemetry_only} or ${has_reason_single_day_telemetry_only} or ${ha
One important thing is that the table contains only the servers with exclusion reasons, and not the full list of servers. So this dimension **MUST** be used always with a `not` clause.

An improvement on the original dimension table would be to include all servers, even those without any exclusion reasons.

2024-02-13 11:36 UTC, ifoukarakis commented on views/marts/product/dim_excludable_servers.view.lkml
> +    sql:  ${has_reason_single_day_security_only} or ${has_reason_custom_build_version_format} or ${has_reason_single_day_server_side_telemetry_only} or ${has_reason_single_day_telemetry_only} or ${ha
Are all these needed? The common subset so far doesn't include the single day telemetry/security ones.

2024-02-13 11:36 UTC, ifoukarakis commented on views/marts/product/dim_excludable_servers.view.lkml
> +    description: "A combination of exclusion reasons which applies to production data analyses"
The label and description are too vague. Let's find a more representative name for this group of exclusion reasons.

2024-02-20 13:40 UTC, catalintomai commented on views/marts/product/dim_excludable_servers.view.lkml
> +    sql: ${has_reason_active_users__registered_users} or ${has_reason_community} ${has_reason_invalid_server_id} or ${has_reason_internal_email} or ${has_reason_custom_build_version_format} or ${has_
missing "or" between this and next?

2024-02-20 19:09 UTC, sri-byte commented on views/marts/product/dim_excludable_servers.view.lkml
> +    sql: ${has_reason_active_users__registered_users} or ${has_reason_community} ${has_reason_invalid_server_id} or ${has_reason_internal_email} or ${has_reason_custom_build_version_format} or ${has_
Fixed this.

2024-02-20 19:26 UTC, catalintomai approved these changes

2024-02-22 15:21 UTC, ifoukarakis approved these changes

2024-02-22 15:41 UTC, merged